version: "3.7"

services: 
    zookeeper:
        image: manga-poll:zookeeper
        hostname: zookeeper
        ports:
            - 2181:2181

    broker:
        image: manga-poll:broker
        hostname: "<your local ip address>"
        ports:
            - 9092:9092
        depends_on: 
            - zookeeper
    
    connect:
        image: manga-poll:connect
        environment: 
            BROKER_URL: <your local ip address>:9092
        ports:
            - 8083:8083
        depends_on: 
            - broker