version: "3.3"

services: 
    zookeeper:
        image: lemonu/manga-poll:zookeeper
        hostname: zookeeper
        environment:
            - ZOOKEEPER_PORT=2181
        ports:
            - 2181:2181

    broker:
        image: lemonu/manga-poll:broker
        hostname: broker
        environment: 
            - ZOOKEEPER_URL=zookeeper:2181
        ports:
            - 9092:9092
        depends_on: 
            - zookeeper
    
    connect:
        image: lemonu/manga-poll:connect
        hostname: connect
        environment: 
            - BROKER_URL=broker:9092
        ports:
            - 8083:8083
        depends_on: 
            - broker