version: "3.3"

services: 
    zookeeper:
        image: lemonu/manga-poll:zookeeper
        hostname: zookeeper
        container_name: zookeeper
        environment:
            - ZOOKEEPER_PORT=2181
        ports:
            - 2181:2181

    broker:
        image: lemonu/manga-poll:broker
        hostname: broker
        container_name: broker
        environment: 
            - ZOOKEEPER_URL=zookeeper:2181
            - LISTENERS=INTERNAL://broker:29092,HOST://broker:9092
            - ADVERTISED_LISTENERS=INTERNAL://broker:29092,HOST://localhost:9092
            - LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,HOST:PLAINTEXT,SSL:SSL,SASL_PLAINTEXT:SASL_PLAINTEXT,SASL_SSL:SASL_SSL
            - INTER_BROKER_LISTENER_NAME=INTERNAL
        ports:
            - 29092:29092
            - 9092:9092
        depends_on: 
            - zookeeper
    
    connect:
        image: lemonu/manga-poll:connect
        hostname: connect
        container_name: connect
        environment: 
            - BROKER_URL=broker:29092
            - OFFSET_FLUSH_INTERVAL_MS=600000
            - PLUGIN_PATH=/opt/connectors
        volumes: 
            - ~/connect-plugins/:/opt/connectors
        ports:
            - 8083:8083
        depends_on: 
            - broker