version: "3.3"

services: 
    zookeeper:
        image: lemonu/manga-poll:zookeeper
        hostname: zookeeper
        environment:
            - ZOOKEEPER_PORT=2181
        ports:
            - 2181:2181

    broker:
        image: lemonu/manga-poll:broker
        hostname: broker                        # Replace this with your physical machine's local network ip
                                                # if you intend to communicate with the contained broker
        environment: 
            - ZOOKEEPER_URL=zookeeper:2181
        ports:
            - 9092:9092
        depends_on: 
            - zookeeper
    
    connect:
        image: lemonu/manga-poll:connect
        hostname: connect
        environment: 
            - BROKER_URL=broker:9092            # Replace "broker" with your physical machine's local network ip
                                                # if you intend to communicate with the contained broker
        ports:
            - 8083:8083
        depends_on: 
            - broker